export const SET_BROWSER_PATH = 'SET_BROWSER_PATH';
export const SET_ACTIVE_SECTION = 'SET_ACTIVE_SECTION';
export const SET_CAROUSEL_INDEX = 'SET_CAROUSEL_INDEX';
export const SET_TOP_BAR_FIXED = 'SET_TOP_BAR_FIXED';
export const SET_CLEAR_CAROUSEL = 'SET_CLEAR_CAROUSEL';
export const SET_EXPAND_CAROUSEL = 'SET_EXPAND_CAROUSEL';
export const RESET_STATE = 'RESET_STATE';